name = "cloudflare-playwright-example"
main = "src/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-09-17"
upload_source_maps = true

[browser]
binding = "MYBROWSER"

[observability]
enabled = true
